name: CI/CD

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2
      
      # Validate branch name
      - name: Validate branch name
        run: |
          echo "Validating branch name..."
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          if [[ "$BRANCH_NAME" != name/* ]]; then
            echo "Branch name does not follow the required pattern."
            exit 1
          fi
          echo "Branch name is valid."

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Install dependencies
      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm install

      # Run tests
      - name: Run tests
        run: |
          echo "Running tests..."
          npm test

      # Build the project
      - name: Build project
        run: |
          echo "Building the project..."
          npm run build
